// src/hooks/useStates.ts
import { useState, useEffect, useMemo } from 'react';

export interface State {
  name: string; // State/Province name
  code?: string; // Optional state code
}

/**
 * Comprehensive mapping of countries to their states/provinces
 * This covers major countries with administrative divisions
 */
const countryStatesMap: Record<string, State[]> = {
  'United States': [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
    { name: 'District of Columbia', code: 'DC' },
  ],
  'Canada': [
    { name: 'Alberta', code: 'AB' },
    { name: 'British Columbia', code: 'BC' },
    { name: 'Manitoba', code: 'MB' },
    { name: 'New Brunswick', code: 'NB' },
    { name: 'Newfoundland and Labrador', code: 'NL' },
    { name: 'Northwest Territories', code: 'NT' },
    { name: 'Nova Scotia', code: 'NS' },
    { name: 'Nunavut', code: 'NU' },
    { name: 'Ontario', code: 'ON' },
    { name: 'Prince Edward Island', code: 'PE' },
    { name: 'Quebec', code: 'QC' },
    { name: 'Saskatchewan', code: 'SK' },
    { name: 'Yukon', code: 'YT' },
  ],
  'Australia': [
    { name: 'Australian Capital Territory', code: 'ACT' },
    { name: 'New South Wales', code: 'NSW' },
    { name: 'Northern Territory', code: 'NT' },
    { name: 'Queensland', code: 'QLD' },
    { name: 'South Australia', code: 'SA' },
    { name: 'Tasmania', code: 'TAS' },
    { name: 'Victoria', code: 'VIC' },
    { name: 'Western Australia', code: 'WA' },
  ],
  'United Kingdom': [
    { name: 'England' },
    { name: 'Scotland' },
    { name: 'Wales' },
    { name: 'Northern Ireland' },
  ],
  'Germany': [
    { name: 'Baden-Württemberg', code: 'BW' },
    { name: 'Bavaria', code: 'BY' },
    { name: 'Berlin', code: 'BE' },
    { name: 'Brandenburg', code: 'BB' },
    { name: 'Bremen', code: 'HB' },
    { name: 'Hamburg', code: 'HH' },
    { name: 'Hesse', code: 'HE' },
    { name: 'Lower Saxony', code: 'NI' },
    { name: 'Mecklenburg-Vorpommern', code: 'MV' },
    { name: 'North Rhine-Westphalia', code: 'NW' },
    { name: 'Rhineland-Palatinate', code: 'RP' },
    { name: 'Saarland', code: 'SL' },
    { name: 'Saxony', code: 'SN' },
    { name: 'Saxony-Anhalt', code: 'ST' },
    { name: 'Schleswig-Holstein', code: 'SH' },
    { name: 'Thuringia', code: 'TH' },
  ],
  'India': [
    { name: 'Andhra Pradesh', code: 'AP' },
    { name: 'Arunachal Pradesh', code: 'AR' },
    { name: 'Assam', code: 'AS' },
    { name: 'Bihar', code: 'BR' },
    { name: 'Chhattisgarh', code: 'CT' },
    { name: 'Goa', code: 'GA' },
    { name: 'Gujarat', code: 'GJ' },
    { name: 'Haryana', code: 'HR' },
    { name: 'Himachal Pradesh', code: 'HP' },
    { name: 'Jharkhand', code: 'JH' },
    { name: 'Karnataka', code: 'KA' },
    { name: 'Kerala', code: 'KL' },
    { name: 'Madhya Pradesh', code: 'MP' },
    { name: 'Maharashtra', code: 'MH' },
    { name: 'Manipur', code: 'MN' },
    { name: 'Meghalaya', code: 'ML' },
    { name: 'Mizoram', code: 'MZ' },
    { name: 'Nagaland', code: 'NL' },
    { name: 'Odisha', code: 'OR' },
    { name: 'Punjab', code: 'PB' },
    { name: 'Rajasthan', code: 'RJ' },
    { name: 'Sikkim', code: 'SK' },
    { name: 'Tamil Nadu', code: 'TN' },
    { name: 'Telangana', code: 'TG' },
    { name: 'Tripura', code: 'TR' },
    { name: 'Uttar Pradesh', code: 'UP' },
    { name: 'Uttarakhand', code: 'UT' },
    { name: 'West Bengal', code: 'WB' },
    { name: 'Andaman and Nicobar Islands', code: 'AN' },
    { name: 'Chandigarh', code: 'CH' },
    { name: 'Dadra and Nagar Haveli and Daman and Diu', code: 'DH' },
    { name: 'Delhi', code: 'DL' },
    { name: 'Jammu and Kashmir', code: 'JK' },
    { name: 'Ladakh', code: 'LA' },
    { name: 'Lakshadweep', code: 'LD' },
    { name: 'Puducherry', code: 'PY' },
  ],
  'China': [
    { name: 'Beijing', code: 'BJ' },
    { name: 'Shanghai', code: 'SH' },
    { name: 'Tianjin', code: 'TJ' },
    { name: 'Chongqing', code: 'CQ' },
    { name: 'Guangdong', code: 'GD' },
    { name: 'Jiangsu', code: 'JS' },
    { name: 'Zhejiang', code: 'ZJ' },
    { name: 'Shandong', code: 'SD' },
    { name: 'Henan', code: 'HA' },
    { name: 'Sichuan', code: 'SC' },
    { name: 'Hubei', code: 'HB' },
    { name: 'Hunan', code: 'HN' },
    { name: 'Fujian', code: 'FJ' },
    { name: 'Anhui', code: 'AH' },
    { name: 'Liaoning', code: 'LN' },
    { name: 'Hebei', code: 'HE' },
    { name: 'Jiangxi', code: 'JX' },
    { name: 'Shanxi', code: 'SX' },
    { name: 'Shaanxi', code: 'SN' },
    { name: 'Yunnan', code: 'YN' },
    { name: 'Guangxi', code: 'GX' },
    { name: 'Inner Mongolia', code: 'NM' },
    { name: 'Guizhou', code: 'GZ' },
    { name: 'Xinjiang', code: 'XJ' },
    { name: 'Heilongjiang', code: 'HL' },
    { name: 'Jilin', code: 'JL' },
    { name: 'Gansu', code: 'GS' },
    { name: 'Qinghai', code: 'QH' },
    { name: 'Hainan', code: 'HI' },
    { name: 'Ningxia', code: 'NX' },
    { name: 'Tibet', code: 'XZ' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Macau', code: 'MO' },
    { name: 'Taiwan', code: 'TW' },
  ],
  'Brazil': [
    { name: 'Acre', code: 'AC' },
    { name: 'Alagoas', code: 'AL' },
    { name: 'Amapá', code: 'AP' },
    { name: 'Amazonas', code: 'AM' },
    { name: 'Bahia', code: 'BA' },
    { name: 'Ceará', code: 'CE' },
    { name: 'Distrito Federal', code: 'DF' },
    { name: 'Espírito Santo', code: 'ES' },
    { name: 'Goiás', code: 'GO' },
    { name: 'Maranhão', code: 'MA' },
    { name: 'Mato Grosso', code: 'MT' },
    { name: 'Mato Grosso do Sul', code: 'MS' },
    { name: 'Minas Gerais', code: 'MG' },
    { name: 'Pará', code: 'PA' },
    { name: 'Paraíba', code: 'PB' },
    { name: 'Paraná', code: 'PR' },
    { name: 'Pernambuco', code: 'PE' },
    { name: 'Piauí', code: 'PI' },
    { name: 'Rio de Janeiro', code: 'RJ' },
    { name: 'Rio Grande do Norte', code: 'RN' },
    { name: 'Rio Grande do Sul', code: 'RS' },
    { name: 'Rondônia', code: 'RO' },
    { name: 'Roraima', code: 'RR' },
    { name: 'Santa Catarina', code: 'SC' },
    { name: 'São Paulo', code: 'SP' },
    { name: 'Sergipe', code: 'SE' },
    { name: 'Tocantins', code: 'TO' },
  ],
  'Mexico': [
    { name: 'Aguascalientes', code: 'AG' },
    { name: 'Baja California', code: 'BC' },
    { name: 'Baja California Sur', code: 'BS' },
    { name: 'Campeche', code: 'CM' },
    { name: 'Chiapas', code: 'CS' },
    { name: 'Chihuahua', code: 'CH' },
    { name: 'Coahuila', code: 'CO' },
    { name: 'Colima', code: 'CL' },
    { name: 'Durango', code: 'DG' },
    { name: 'Guanajuato', code: 'GT' },
    { name: 'Guerrero', code: 'GR' },
    { name: 'Hidalgo', code: 'HG' },
    { name: 'Jalisco', code: 'JA' },
    { name: 'México', code: 'ME' },
    { name: 'Michoacán', code: 'MI' },
    { name: 'Morelos', code: 'MO' },
    { name: 'Nayarit', code: 'NA' },
    { name: 'Nuevo León', code: 'NL' },
    { name: 'Oaxaca', code: 'OA' },
    { name: 'Puebla', code: 'PU' },
    { name: 'Querétaro', code: 'QT' },
    { name: 'Quintana Roo', code: 'QR' },
    { name: 'San Luis Potosí', code: 'SL' },
    { name: 'Sinaloa', code: 'SI' },
    { name: 'Sonora', code: 'SO' },
    { name: 'Tabasco', code: 'TB' },
    { name: 'Tamaulipas', code: 'TM' },
    { name: 'Tlaxcala', code: 'TL' },
    { name: 'Veracruz', code: 'VE' },
    { name: 'Yucatán', code: 'YU' },
    { name: 'Zacatecas', code: 'ZA' },
    { name: 'Mexico City', code: 'DF' },
  ],
  'Japan': [
    { name: 'Hokkaido', code: '01' },
    { name: 'Aomori', code: '02' },
    { name: 'Iwate', code: '03' },
    { name: 'Miyagi', code: '04' },
    { name: 'Akita', code: '05' },
    { name: 'Yamagata', code: '06' },
    { name: 'Fukushima', code: '07' },
    { name: 'Ibaraki', code: '08' },
    { name: 'Tochigi', code: '09' },
    { name: 'Gunma', code: '10' },
    { name: 'Saitama', code: '11' },
    { name: 'Chiba', code: '12' },
    { name: 'Tokyo', code: '13' },
    { name: 'Kanagawa', code: '14' },
    { name: 'Niigata', code: '15' },
    { name: 'Toyama', code: '16' },
    { name: 'Ishikawa', code: '17' },
    { name: 'Fukui', code: '18' },
    { name: 'Yamanashi', code: '19' },
    { name: 'Nagano', code: '20' },
    { name: 'Gifu', code: '21' },
    { name: 'Shizuoka', code: '22' },
    { name: 'Aichi', code: '23' },
    { name: 'Mie', code: '24' },
    { name: 'Shiga', code: '25' },
    { name: 'Kyoto', code: '26' },
    { name: 'Osaka', code: '27' },
    { name: 'Hyogo', code: '28' },
    { name: 'Nara', code: '29' },
    { name: 'Wakayama', code: '30' },
    { name: 'Tottori', code: '31' },
    { name: 'Shimane', code: '32' },
    { name: 'Okayama', code: '33' },
    { name: 'Hiroshima', code: '34' },
    { name: 'Yamaguchi', code: '35' },
    { name: 'Tokushima', code: '36' },
    { name: 'Kagawa', code: '37' },
    { name: 'Ehime', code: '38' },
    { name: 'Kochi', code: '39' },
    { name: 'Fukuoka', code: '40' },
    { name: 'Saga', code: '41' },
    { name: 'Nagasaki', code: '42' },
    { name: 'Kumamoto', code: '43' },
    { name: 'Oita', code: '44' },
    { name: 'Miyazaki', code: '45' },
    { name: 'Kagoshima', code: '46' },
    { name: 'Okinawa', code: '47' },
  ],
  'France': [
    { name: 'Île-de-France', code: 'IDF' },
    { name: 'Auvergne-Rhône-Alpes', code: 'ARA' },
    { name: 'Nouvelle-Aquitaine', code: 'NAQ' },
    { name: 'Occitanie', code: 'OCC' },
    { name: 'Provence-Alpes-Côte d\'Azur', code: 'PAC' },
    { name: 'Grand Est', code: 'GES' },
    { name: 'Hauts-de-France', code: 'HDF' },
    { name: 'Normandy', code: 'NOR' },
    { name: 'Brittany', code: 'BRE' },
    { name: 'Pays de la Loire', code: 'PDL' },
    { name: 'Centre-Val de Loire', code: 'CVL' },
    { name: 'Burgundy-Franche-Comté', code: 'BFC' },
    { name: 'Corsica', code: 'COR' },
  ],
  'Italy': [
    { name: 'Abruzzo', code: 'ABR' },
    { name: 'Basilicata', code: 'BAS' },
    { name: 'Calabria', code: 'CAL' },
    { name: 'Campania', code: 'CAM' },
    { name: 'Emilia-Romagna', code: 'EMR' },
    { name: 'Friuli-Venezia Giulia', code: 'FVG' },
    { name: 'Lazio', code: 'LAZ' },
    { name: 'Liguria', code: 'LIG' },
    { name: 'Lombardy', code: 'LOM' },
    { name: 'Marche', code: 'MAR' },
    { name: 'Molise', code: 'MOL' },
    { name: 'Piedmont', code: 'PIE' },
    { name: 'Puglia', code: 'PUG' },
    { name: 'Sardinia', code: 'SAR' },
    { name: 'Sicily', code: 'SIC' },
    { name: 'Trentino-Alto Adige', code: 'TAA' },
    { name: 'Tuscany', code: 'TOS' },
    { name: 'Umbria', code: 'UMB' },
    { name: 'Valle d\'Aosta', code: 'VDA' },
    { name: 'Veneto', code: 'VEN' },
  ],
  'Spain': [
    { name: 'Andalusia', code: 'AN' },
    { name: 'Aragon', code: 'AR' },
    { name: 'Asturias', code: 'AS' },
    { name: 'Balearic Islands', code: 'IB' },
    { name: 'Basque Country', code: 'PV' },
    { name: 'Canary Islands', code: 'CN' },
    { name: 'Cantabria', code: 'CB' },
    { name: 'Castile and León', code: 'CL' },
    { name: 'Castile-La Mancha', code: 'CM' },
    { name: 'Catalonia', code: 'CT' },
    { name: 'Extremadura', code: 'EX' },
    { name: 'Galicia', code: 'GA' },
    { name: 'La Rioja', code: 'RI' },
    { name: 'Madrid', code: 'MD' },
    { name: 'Murcia', code: 'MC' },
    { name: 'Navarre', code: 'NA' },
    { name: 'Valencia', code: 'VC' },
  ],
  'South Africa': [
    { name: 'Eastern Cape', code: 'EC' },
    { name: 'Free State', code: 'FS' },
    { name: 'Gauteng', code: 'GP' },
    { name: 'KwaZulu-Natal', code: 'KZN' },
    { name: 'Limpopo', code: 'LP' },
    { name: 'Mpumalanga', code: 'MP' },
    { name: 'Northern Cape', code: 'NC' },
    { name: 'North West', code: 'NW' },
    { name: 'Western Cape', code: 'WC' },
  ],
  'Netherlands': [
    { name: 'Drenthe', code: 'DR' },
    { name: 'Flevoland', code: 'FL' },
    { name: 'Friesland', code: 'FR' },
    { name: 'Gelderland', code: 'GE' },
    { name: 'Groningen', code: 'GR' },
    { name: 'Limburg', code: 'LI' },
    { name: 'North Brabant', code: 'NB' },
    { name: 'North Holland', code: 'NH' },
    { name: 'Overijssel', code: 'OV' },
    { name: 'South Holland', code: 'ZH' },
    { name: 'Utrecht', code: 'UT' },
    { name: 'Zeeland', code: 'ZE' },
  ],
  'Switzerland': [
    { name: 'Aargau', code: 'AG' },
    { name: 'Appenzell Ausserrhoden', code: 'AR' },
    { name: 'Appenzell Innerrhoden', code: 'AI' },
    { name: 'Basel-Landschaft', code: 'BL' },
    { name: 'Basel-Stadt', code: 'BS' },
    { name: 'Bern', code: 'BE' },
    { name: 'Fribourg', code: 'FR' },
    { name: 'Geneva', code: 'GE' },
    { name: 'Glarus', code: 'GL' },
    { name: 'Graubünden', code: 'GR' },
    { name: 'Jura', code: 'JU' },
    { name: 'Lucerne', code: 'LU' },
    { name: 'Neuchâtel', code: 'NE' },
    { name: 'Nidwalden', code: 'NW' },
    { name: 'Obwalden', code: 'OW' },
    { name: 'Schaffhausen', code: 'SH' },
    { name: 'Schwyz', code: 'SZ' },
    { name: 'Solothurn', code: 'SO' },
    { name: 'St. Gallen', code: 'SG' },
    { name: 'Thurgau', code: 'TG' },
    { name: 'Ticino', code: 'TI' },
    { name: 'Uri', code: 'UR' },
    { name: 'Valais', code: 'VS' },
    { name: 'Vaud', code: 'VD' },
    { name: 'Zug', code: 'ZG' },
    { name: 'Zürich', code: 'ZH' },
  ],
  'Sweden': [
    { name: 'Stockholm', code: 'AB' },
    { name: 'Västerbotten', code: 'AC' },
    { name: 'Norrbotten', code: 'BD' },
    { name: 'Uppsala', code: 'C' },
    { name: 'Södermanland', code: 'D' },
    { name: 'Östergötland', code: 'E' },
    { name: 'Jönköping', code: 'F' },
    { name: 'Kronoberg', code: 'G' },
    { name: 'Kalmar', code: 'H' },
    { name: 'Gotland', code: 'I' },
    { name: 'Blekinge', code: 'K' },
    { name: 'Skåne', code: 'M' },
    { name: 'Halland', code: 'N' },
    { name: 'Västra Götaland', code: 'O' },
    { name: 'Värmland', code: 'S' },
    { name: 'Örebro', code: 'T' },
    { name: 'Västmanland', code: 'U' },
    { name: 'Dalarna', code: 'W' },
    { name: 'Gävleborg', code: 'X' },
    { name: 'Västernorrland', code: 'Y' },
    { name: 'Jämtland', code: 'Z' },
  ],
};

/**
 * Hook to get states/provinces for a given country
 * @param countryName - The name of the country (must match exactly with keys in countryStatesMap)
 * @returns Array of states/provinces for the country, sorted alphabetically
 */
export const useStates = (countryName?: string | null) => {
  const states = useMemo(() => {
    if (!countryName) {
      return [];
    }

    // Try exact match first
    let countryStates = countryStatesMap[countryName];

    // Try case-insensitive match if exact match fails
    if (!countryStates) {
      const normalizedCountry = countryName.toLowerCase();
      const matchingKey = Object.keys(countryStatesMap).find(
        key => key.toLowerCase() === normalizedCountry
      );
      if (matchingKey) {
        countryStates = countryStatesMap[matchingKey];
      }
    }

    if (!countryStates) {
      return [];
    }

    // Return sorted states
    return [...countryStates].sort((a, b) => a.name.localeCompare(b.name));
  }, [countryName]);

  return {
    states,
    loading: false,
    hasStates: states.length > 0,
  };
};

/**
 * Get states for a country (static function for use outside components)
 */
export const getStatesByCountry = (countryName?: string | null): State[] => {
  if (!countryName) {
    return [];
  }

  let countryStates = countryStatesMap[countryName];

  if (!countryStates) {
    const normalizedCountry = countryName.toLowerCase();
    const matchingKey = Object.keys(countryStatesMap).find(
      key => key.toLowerCase() === normalizedCountry
    );
    if (matchingKey) {
      countryStates = countryStatesMap[matchingKey];
    }
  }

  if (!countryStates) {
    return [];
  }

  return [...countryStates].sort((a, b) => a.name.localeCompare(b.name));
};

