import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@app/config/constants/navigation.constant'

import type { NavigationTree } from '@app/types/navigation'
import { LEARNER } from '@app/config/constants/roles.constant'

const upperNavigation: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Home',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'nav.dashboard.dashboard',
                path: '/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.dashboard.item1',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.dashboard.application',
                path: '/application',
                title: 'Application',
                translateKey: 'nav.dashboard.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.dashboard.calender',
                path: '/calender',
                title: 'Calendar',
                translateKey: 'nav.dashboard.item4',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'Explore',
        path: '/explore',
        title: 'Explore',
        translateKey: 'nav.explore',
        icon: 'Learning',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'nav.Explore.courses',
                path: '/courses-list',
                title: 'Courses',
                translateKey: 'nav.Explore.item1',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Explore.Universities',
                path: '/universities-list',
                title: 'Universities',
                translateKey: 'nav.Explore.item2',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Explore.interests',
                path: '/interests',
                title: 'Interests',
                translateKey: 'nav.Explore.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Explore.skills',
                path: '/skills',
                title: 'Skills',
                translateKey: 'nav.Explore.item4',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER],
                subMenu: [],
            },
            // {
            //     key: 'nav.Explore.events',
            //     path: '/events-list',
            //     title: 'Events',
            //     translateKey: 'nav.Explore.item4',
            //     icon: 'learningMenu',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'Collapse Menu',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item2',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'Collapse menu item 2',
    //             translateKey: 'nav.collapseMenu.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Help',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'My Portal',
    //             translateKey: 'nav.groupMenu.single.item1',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },

    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'My Mail box',
    //             translateKey: 'nav.groupMenu.collapse.collapse.item3',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [
    //                 // {
    //                 //     key: 'groupMenu.collapse.item1',
    //                 //     path: '/group-collapse-menu-item-view-1',
    //                 //     title: 'Menu item 1',
    //                 //     translateKey: 'nav.groupMenu.collapse.item1',
    //                 //     icon: '',
    //                 //     type: NAV_ITEM_TYPE_ITEM,
    //                 //     authority: [],
    //                 //     subMenu: [],
    //                 // },
    //                 // {
    //                 //     key: 'groupMenu.collapse.item2',
    //                 //     path: '/group-collapse-menu-item-view-2',
    //                 //     title: 'Menu item 2',
    //                 //     translateKey: 'nav.groupMenu.collapse.item2',
    //                 //     icon: '',
    //                 //     type: NAV_ITEM_TYPE_ITEM,
    //                 //     authority: [],
    //                 //     subMenu: [],
    //                 // },
    //             ],
    //         },
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Customer Support',
    //             translateKey: 'nav.groupMenu.single.item2',
    //             icon: 'groupSingl`eMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },

]


const belowNavigation: NavigationTree[] = [
    {
        key: 'nav.Explore.events',
        path: '/events-list',
        title: 'Events and Activities',
        translateKey: 'nav.Explore.item4',
        icon: 'events',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'Portfolio',
        path: '/portfolio',
        title: 'My Portfolio',
        translateKey: 'nav.learning',
        icon: 'Learning',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
        ],
    },
    {
        key: 'community.wall',
        path: '/community/wall',
        title: 'Communities',
        translateKey: 'nav.Social.item3',
        icon: 'community',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'community.wall',
                path: '/community/wall',
                title: 'Wall',
                translateKey: 'nav.Social.item1',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // my communities
            {
                key: 'community.mycommunities',
                path: '/community/mycommunities',
                title: 'My Communities',
                translateKey: 'nav.Social.item1',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'community.discover',
                path: '/community/discover',
                title: 'Discover',
                translateKey: 'nav.Social.item1',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    {
        key: 'Social',
        path: '/social',
        title: 'Social Connect',
        translateKey: 'nav.Social',
        icon: 'Learning',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'nav.Social.reels',
                path: '/reels',
                title: 'Reels',
                translateKey: 'nav.Social.item1',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Social.blogs',
                path: '/blogs',
                title: 'Blogs',
                translateKey: 'nav.Social.item2',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Social.mentoring',
                path: '/mentoring',
                title: 'Mentoring',
                translateKey: 'nav.Social.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Social.news-letter',
                path: '/news-letter',
                title: 'News Letters',
                translateKey: 'nav.Social.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    {
        key: 'nav.Help',
        path: '/help',
        title: 'Help',
        translateKey: 'nav.Help',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'nav.Help.mail-box',
                path: '/help/mail-box',
                title: 'My Mail box',
                translateKey: 'nav.Help.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Help.customer-support',
                path: '/customer-support',
                title: 'Customer Support',
                translateKey: 'nav.Help.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'nav.Help.privacy-policy',
                path: '/privacy-and-policy',
                title: 'Privacy Policy',
                translateKey: 'nav.Help.item3',
                icon: 'learningMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

        ],
    },
]

const navigationConfig = {
    upperNavigation,
    belowNavigation,
}

export default navigationConfig;